"""Pre-fetch ISRIC SoilGrids soil data for every supported region and cache it.

Run occasionally (soil changes slowly), NOT in the request path:

    python scripts/prefetch_soil.py

It walks the division centroids in data/regions.json, queries SoilGrids for each,
and writes data/soil_cache.json. Respects SoilGrids' ~5 calls/minute fair-use
limit by sleeping between calls. Points that fail are skipped (not faked).
"""

import os
import sys
import json
import time
from datetime import datetime, timezone

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from services import datastore  # noqa: E402
from services import soil as soil_svc  # noqa: E402

SLEEP_SECONDS = 15  # ~4 calls/min, under the ~5/min fair-use limit.


def main():
    regions = datastore.load("regions")
    provinces = regions.get("provinces", {})
    points = []

    targets = []
    for p_key, prov in provinces.items():
        for div_name, div in prov.get("divisions", {}).items():
            if div.get("lat") and div.get("lon"):
                targets.append((p_key, div_name, div["lat"], div["lon"]))

    print(f"Prefetching soil for {len(targets)} regions "
          f"(~{len(targets) * SLEEP_SECONDS // 60} min with rate limiting)...")

    for i, (p_key, div_name, lat, lon) in enumerate(targets, 1):
        print(f"[{i}/{len(targets)}] {p_key}/{div_name} ({lat},{lon}) ...", end=" ")
        soil = soil_svc.fetch_live(lat, lon)
        if soil.get("available"):
            points.append({"province": p_key, "division": div_name,
                           "lat": lat, "lon": lon, "soil": soil})
            print("ok")
        else:
            print(f"skipped ({soil.get('reason')})")
        if i < len(targets):
            time.sleep(SLEEP_SECONDS)

    out = {
        "_README": "Auto-generated by scripts/prefetch_soil.py. Re-run occasionally.",
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "points": points,
    }
    path = os.path.join(datastore.DATA_DIR, "soil_cache.json")
    with open(path, "w", encoding="utf-8") as f:
        json.dump(out, f, ensure_ascii=False, indent=1)
    print(f"\nWrote {len(points)} soil points to {path}")


if __name__ == "__main__":
    main()
